import assert from 'node:assert/strict';
import test from 'node:test';
import {MatchSimulation} from '../server/simulation.ts';
import {WEAPONS,damageAtDistance} from '../shared/weapons.ts';
import {traceWeaponBurst} from '../shared/combat.ts';
const create=()=>new MatchSimulation([{id:'a',nickname:'A',x:8,z:-10}]);
test('pistol start, purchases idempotent, ammo overflow and repeat equip preserve resources',()=>{const s=create(),p=s.player('a');assert.equal(p.weapon,'pistol');assert.equal(p.coins,0);assert.deepEqual(Object.keys(p.inventory),['pistol']);p.coins=2000;assert.equal(s.buy('a','buy_weapon','rifle','1').ok,true);assert.equal(p.coins,1100);s.buy('a','buy_weapon','rifle','1');assert.equal(p.coins,1100);assert.equal(p.reserve,0);p.ammo=2;s.buy('a','equip','rifle','2');assert.equal(p.ammo,2);for(let i=0;i<4;i++)assert.equal(s.buy('a','buy_ammo','rifle','ammo'+i).ok,true);assert.equal(s.buy('a','buy_ammo','rifle','overflow').ok,false);});
test('unlimited pistol reload and respawn retain ammunition',()=>{const s=create(),p=s.player('a');p.ammo=1;p.inventory.pistol.ammo=1;assert.equal(s.reload('a'),true);s.tick(1.31);assert.equal(p.ammo,12);p.ammo=3;p.inventory.pistol.ammo=3;p.alive=false;p.respawnLeft=.1;s.tick(.2);assert.equal(p.ammo,3);});
test('shop denies queued movement and recent firing',()=>{const s=create(),p=s.player('a');p.coins=2000;s.applyInput('a',{sequence:1,moveX:1,moveZ:0,yaw:0,pitch:0,jump:false,crouch:false,sprint:false,clientTime:0});assert.equal(s.buy('a','buy_weapon','rifle','1').ok,false);});
test('falloff and burst deterministic',()=>{assert.equal(damageAtDistance('pistol',40),9);assert.equal(damageAtDistance('rifle',0,true),105);const args=[{x:8,y:1.68,z:-10},0,0,'shotgun',false,[],20];const a=traceWeaponBurst(...args);assert.equal(a.length,9);assert.deepEqual(a,traceWeaponBurst(...args));assert.notDeepEqual(a,traceWeaponBurst(...args.slice(0,6),21));assert.equal(WEAPONS.smg.cadence,60/850);});
test('850rpm remains accurate at 20Hz without accepting early or duplicate shots',()=>{const s=create(),p=s.player('a');p.coins=450;s.buy('a','buy_weapon','smg','smg');p.cooldown=0;let shots=0;for(let n=0;n<20;n++){if(s.fire('a',{sequence:n*2,weapon:'smg',yaw:0,pitch:0,clientTime:0}))shots++;assert.equal(s.fire('a',{sequence:n*2,weapon:'smg',yaw:0,pitch:0,clientTime:0}),false);s.tick(.05);}assert.equal(shots,14);});
test('shotgun aggregates pellet hits and rewards one capped kill',()=>{const s=new MatchSimulation([{id:'a',nickname:'A',x:8,z:-8},{id:'b',nickname:'B',x:8,z:-10,isBot:true}]);const p=s.player('a'),b=s.player('b');p.coins=6000;s.buy('a','buy_weapon','shotgun','gun');p.cooldown=0;p.coins=5990;b.health=1;b.spawnProtection=0;assert.equal(s.fire('a',{sequence:1,weapon:'shotgun',yaw:0,pitch:-.15,clientTime:0}),true);assert.equal(p.kills,1);assert.equal(p.coins,6000);assert.equal(s.events.filter(e=>e.type==='kill').length,1);assert.equal(s.events.find(e=>e.type==='shot').ends.length,9);assert.equal(s.buy('a','buy_ammo','shotgun','hot').reason,'COMBAT_COOLDOWN');});
test('bots buy with earned balance and reload infinite pistol',()=>{const s=new MatchSimulation([{id:'bot',nickname:'Bot',x:8,z:-8,isBot:true}]);const p=s.player('bot');p.coins=450;s.tick(.05);assert.equal(p.primary,'smg');assert.equal(p.coins,0);const t=new MatchSimulation([{id:'bot',nickname:'Bot',x:8,z:-8,isBot:true}]);t.player('bot').ammo=0;t.tick(.05);assert.ok(t.player('bot').reloadLeft>0);});
test('queued shop validates after movement and fire actions',()=>{const s=create(),p=s.player('a');p.coins=900;const input=(sequence,moveX)=>({sequence,moveX,moveZ:0,yaw:0,pitch:0,jump:false,crouch:false,sprint:false,clientTime:0,dt:.01});s.applyInput('a',input(1,1));s.applyInput('a',input(2,0));let result;s.queueBuy('a','buy_weapon','rifle','q',r=>result=r);assert.equal(result,undefined);s.tick(.05);assert.equal(result.ok,true);p.cooldown=0;s.queueFire('a',{sequence:3,weapon:'rifle',yaw:0,pitch:0,clientTime:0});s.queueBuy('a','equip','pistol','q2',r=>result=r);s.tick(.05);assert.equal(result.reason,'COMBAT_COOLDOWN');});
test('damage after idle cannot grant same-tick double fire; sprint blocks shots',()=>{const s=create(),p=s.player('a');s.tick(1);p.lastCombat=1;const fire=n=>s.fire('a',{sequence:n,weapon:'pistol',yaw:0,pitch:0,clientTime:0});assert.equal(fire(1),true);assert.equal(fire(2),false);s.tick(1);p.input.sprint=true;p.input.moveZ=1;assert.equal(fire(3),false);});
test('queued purchase is invalidated by life reset',()=>{const s=create();s.player('a').coins=900;let result;s.queueBuy('a','buy_weapon','rifle','old',r=>result=r);s.resetInputs('a');s.tick(.05);assert.equal(result.reason,'STALE_LIFE');assert.equal(s.player('a').coins,900);});
test('NPCs save for varied primaries and use pistol when paid ammo is exhausted',()=>{const s=new MatchSimulation(['a','b','c','d'].map(id=>({id,nickname:id,x:8,z:-8,isBot:true})));for(const p of s.players.values())p.coins=1500;s.tick(.05);assert.deepEqual([...s.players.values()].map(p=>p.primary),['smg','shotgun','rifle','sniper']);const p=s.player('a');p.ammo=0;p.reserve=0;p.inventory.smg={ammo:0,reserve:0};p.coins=0;s.tick(.05);assert.equal(p.weapon,'pistol');});

test('sniper NPC engages a visible target beyond legacy 35m range',()=>{const s=new MatchSimulation([{id:'human',nickname:'Human',x:-19,z:-19},{id:'bot',nickname:'Bot',x:-19,z:19,isBot:true}]);const p=s.player('bot');p.coins=1500;s.buy('bot','buy_weapon','sniper','sniper');let shots=0;for(let i=0;i<200;i++){s.tick(.05);shots+=s.drainEvents().filter(e=>e.type==='shot'&&e.actorId==='bot').length;}assert.ok(shots>0);});
