'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import type { RoomPlayer,ServerMessage } from '../shared/protocol.ts';
import { GameConnection } from '../lib/network/client.ts';
import { MultiplayerGame,type MultiplayerHud } from '../lib/game/multiplayer.ts';

const SERVER_URL=((import.meta as ImportMeta&{env?:Record<string,string>}).env?.VITE_GAME_SERVER_URL)??'ws://127.0.0.1:3001/game';
const initialHud:MultiplayerHud={health:100,ammo:30,reserve:120,kills:0,deaths:0,remaining:300,latency:0,connected:false,weapon:'rifle',reloadLeft:0,alive:true,protection:0,aiming:false,hitMarker:0,headshot:false,hurt:0,result:null};

export default function Multiplayer({onBack}:{onBack:()=>void}){
  const connection=useMemo(()=>new GameConnection({url:SERVER_URL}),[]),mount=useRef<HTMLDivElement>(null),engine=useRef<MultiplayerGame|null>(null);
  const [nickname,setNickname]=useState(typeof localStorage==='undefined'?'':localStorage.getItem('zero-point-nickname')??''),[code,setCode]=useState(''),[botCount,setBotCount]=useState(0),[difficulty,setDifficulty]=useState<'easy'|'normal'|'hard'>('normal'),[room,setRoom]=useState<Extract<ServerMessage,{type:'room_state'}>>(),[playerId,setPlayerId]=useState(''),[status,setStatus]=useState('正在连接服务器…'),[hud,setHud]=useState(initialHud);
  useEffect(()=>{const unsubscribe=connection.subscribe(message=>{if(message.type==='welcome'){setPlayerId(message.playerId);setStatus('已连接');}if(message.type==='room_state')setRoom(message);if(message.type==='error')setStatus(({ROOM_NOT_FOUND:'房间不存在，请检查房间码',ROOM_FULL:'房间已满',MATCH_ALREADY_STARTED:'比赛已经开始',VERSION_MISMATCH:'游戏版本不一致，请更新游戏'} as Record<string,string>)[message.code]??`服务器提示：${message.code}`);if(message.type==='match_started')setStatus('比赛开始');});connection.connect();return()=>{unsubscribe();engine.current?.dispose();connection.close();};},[connection]);
  useEffect(()=>{if(room?.phase==='playing'&&playerId&&mount.current&&!engine.current)engine.current=new MultiplayerGame(mount.current,connection,playerId,setHud);},[room?.phase,playerId,connection]);
  const validName=nickname.trim().length>=1&&nickname.trim().length<=16;const saveName=()=>localStorage.setItem('zero-point-nickname',nickname.trim());
  const sendCreate=()=>{if(!validName)return;saveName();connection.send({type:'create_room',nickname:nickname.trim(),humanLimit:4,botCount,difficulty});setStatus('正在创建房间…');};
  const sendJoin=()=>{if(!validName||!/^[A-HJ-NP-Z2-9]{6}$/.test(code))return;saveName();connection.send({type:'join_room',nickname:nickname.trim(),roomCode:code});setStatus('正在加入房间…');};
  const leave=()=>{engine.current?.dispose();engine.current=null;connection.leave();onBack();};
  if(room?.phase==='playing')return <main className="multi-game"><div ref={mount} className="viewport"/><header className="multi-hud"><strong>零点行动 · 联机</strong><span>{room.roomCode}</span><b>{String(Math.floor(hud.remaining/60)).padStart(2,'0')}:{String(Math.floor(hud.remaining%60)).padStart(2,'0')}</b><span>击杀 {hud.kills} / 阵亡 {hud.deaths}</span><span>生命 {hud.health}　{hud.weapon==='rifle'?'步枪':'手枪'} {hud.ammo}/{hud.reserve}</span><button onClick={leave}>退出房间</button></header><div className={`crosshair ${hud.aiming?'aiming':''}`}><i/><i/><i/><i/><b/></div>{hud.hitMarker>0&&<div key={hud.hitMarker} className={`multi-hit-marker ${hud.headshot?'headshot':''}`}>×</div>}{hud.hurt>0&&<div key={hud.hurt} className="multi-damage-vignette"/>}{hud.reloadLeft>0&&<div className="multi-action-note">正在换弹…</div>}{hud.protection>0&&!hud.result&&<div className="multi-protection">出生保护 {hud.protection.toFixed(1)} 秒</div>}{!hud.alive&&!hud.result&&<div className="multi-death">你已阵亡，3 秒后重生</div>}{hud.result&&<div className="multi-death">{hud.result==='win'?'比赛胜利':hud.result==='loss'?'比赛失败':'比赛结束：平局'}<small>按 Esc 释放鼠标，然后点击右上角退出房间</small></div>}{!hud.connected&&!hud.result&&<div className="network-overlay">连接中断，正在自动重连…</div>}</main>;
  return <main className="multiplayer-screen"><section className="multiplayer-card"><small>INTERNET MULTIPLAYER</small><h1>互联网联机<span>.</span></h1><p className="server-status">{status}</p>{!room?<><label>你的昵称<input value={nickname} maxLength={16} onChange={e=>setNickname(e.target.value)} placeholder="1–16 个字符"/></label><div className="room-options"><label>人机补位<select value={botCount} onChange={e=>setBotCount(Number(e.target.value))}><option value="0">不添加</option><option value="1">1 名</option><option value="2">2 名</option><option value="3">3 名</option></select></label><label>人机难度<select value={difficulty} onChange={e=>setDifficulty(e.target.value as typeof difficulty)}><option value="easy">新兵</option><option value="normal">标准</option><option value="hard">精英</option></select></label></div><button className="primary-button" disabled={!validName} onClick={sendCreate}>创建房间</button><div className="join-row"><input aria-label="房间码" value={code} maxLength={6} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[O0I1]/g,''))} placeholder="六位房间码"/><button disabled={!validName||code.length!==6} onClick={sendJoin}>加入</button></div><button className="text-button" onClick={()=>{connection.close();onBack();}}>返回模式选择</button></>:<Lobby room={room} playerId={playerId} connection={connection} onLeave={leave}/>}</section></main>;
}

function Lobby({room,playerId,connection,onLeave}:{room:Extract<ServerMessage,{type:'room_state'}>;playerId:string;connection:GameConnection;onLeave:()=>void}){
  const me=room.players.find(p=>p.playerId===playerId),host=room.hostPlayerId===playerId,allReady=room.players.filter(p=>!p.isBot&&p.connected).every(p=>p.ready);
  return <><div className="room-code"><span>房间码</span><strong>{room.roomCode}</strong><button onClick={()=>navigator.clipboard?.writeText(room.roomCode)}>复制</button></div><div className="player-list">{room.players.map((player:RoomPlayer)=><div key={player.playerId}><span>{player.isHost?'★ ':''}{player.nickname}</span><b>{player.connected?(player.ready?'已准备':'未准备'):'已掉线'}</b></div>)}</div>{host&&<div className="room-options"><label>人机补位<select value={room.botCount} onChange={e=>connection.send({type:'configure_room',botCount:Number(e.target.value),difficulty:room.difficulty})}>{[0,1,2,3].map(n=><option key={n} value={n}>{n} 名</option>)}</select></label><label>难度<select value={room.difficulty} onChange={e=>connection.send({type:'configure_room',botCount:room.botCount,difficulty:e.target.value as 'easy'|'normal'|'hard'})}><option value="easy">新兵</option><option value="normal">标准</option><option value="hard">精英</option></select></label></div>}<button className="primary-button" onClick={()=>connection.send({type:'set_ready',ready:!me?.ready})}>{me?.ready?'取消准备':'准备'}</button>{host&&<button className="primary-button secondary" disabled={!allReady} onClick={()=>connection.send({type:'start_match'})}>开始比赛</button>}<button className="text-button" onClick={onLeave}>离开房间</button></>;
}
