import { Cross, Crosshair, Play, Shield, Skull, Volume2, VolumeX, Zap } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import type { MultiplayerHud } from '../lib/game/multiplayer.ts';
import type { GameSettings } from '../lib/game/settings.ts';
import { Radar } from './game';

export function MultiplayerMatch({hud,roomCode,settings,onSettings,onOpen,onResume,onLeave}:{hud:MultiplayerHud;roomCode:string;settings:GameSettings;onSettings:(value:GameSettings)=>void;onOpen:()=>void;onResume:()=>void;onLeave:()=>void}){
  const time=`${String(Math.floor(hud.remaining/60)).padStart(2,'0')}:${String(Math.floor(hud.remaining%60)).padStart(2,'0')}`;
  const reloadTotal=hud.weapon==='rifle'?1.9:1.3;
  return <>
    <header className="topbar"><div className="brand"><span className="brand-symbol"><Crosshair size={25}/></span><span>ZERO / POINT<small>联机 · {roomCode}</small></span></div><div className="scoreboard"><div className="your-score"><span>你</span><strong>{String(hud.kills).padStart(2,'0')}</strong></div><div className="match-clock"><small>击杀竞赛 · 目标 15</small><b>{time}</b></div><div className="enemy-score"><strong>{String(hud.leaderKills).padStart(2,'0')}</strong><span>{hud.leaderName||'领先对手'}</span></div></div><div className="top-actions"><button aria-label={settings.sound?'关闭音效':'打开音效'} onClick={()=>onSettings({...settings,sound:!settings.sound})}>{settings.sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="pause-button" onClick={onOpen}>ESC</button></div></header>
    <div className="radar-hud"><Radar state={{x:hud.x,z:hud.z,yaw:hud.yaw,bots:hud.enemies}}/><div><span className="live-dot"/> 七号仓库 <span>{Math.round(hud.latency)} ms</span></div></div>
    <div className="kill-feed" aria-live="polite">{hud.feed.map(f=><div key={f.id} className={f.attacker==='你'?'friendly':''}><strong>{f.attacker}</strong>{f.headshot?<Crosshair size={15}/>:<Zap size={14}/>}<span>{f.victim}</span>{f.headshot&&<small>爆头</small>}</div>)}</div>
    {hud.alive&&!hud.menuOpen&&!hud.result&&<><div className={`crosshair ${hud.aiming?'aiming':''}`}><i/><i/><i/><i/><b/></div>{hud.hitMarker>0&&<div key={hud.hitMarker} className={`multi-hit-marker ${hud.headshot?'headshot':''}`}>×</div>}{hud.protection>0&&<div className="protection"><Shield size={15}/> 出生保护 {Math.ceil(hud.protection)}s</div>}{hud.reloadLeft>0&&<div className="reload-indicator"><span>正在换弹</span><div><i style={{width:`${Math.max(0,Math.min(100,(1-hud.reloadLeft/reloadTotal)*100))}%`}}/></div></div>}{hud.ammo===0&&hud.reloadLeft<=0&&<div className="reload-indicator">{hud.reserve>0?'按 R 换弹':'备用弹药耗尽 · 按 1 / 2 切换武器'}</div>}</>}
    {hud.hurt>0&&<div key={hud.hurt} className="multi-damage-vignette"/>}
    <div className="bottom-hud"><div className={`health-block ${hud.health<30?'low':''}`}><Cross size={27}/><strong>{hud.health}</strong><div><span>生命值</span><div className="health-track"><i style={{width:`${hud.health}%`}}/></div></div></div><div className="hud-tip"><kbd>1</kbd> 步枪 <kbd>2</kbd> 手枪 <span>·</span><kbd>R</kbd> 换弹</div><div className="ammo-block"><div className="weapon-label"><span>{hud.weapon==='rifle'?'AR-4':'P-12'}</span><small>{hud.weapon==='rifle'?'突击步枪 / 自动':'战术手枪 / 连发'}</small></div><div className="ammo-count"><strong className={hud.ammo<6?'low-ammo':''}>{String(hud.ammo).padStart(2,'0')}</strong><span>/ {hud.reserve}</span></div></div></div>
    {!hud.alive&&!hud.result&&!hud.menuOpen&&<div className="death-overlay"><Skull size={34}/><small>你已阵亡</small><h2>重返战场</h2><div className="respawn-number">{Math.max(1,Math.ceil(hud.respawnLeft))}</div><p>正在寻找安全出生点</p></div>}
    {hud.menuOpen&&!hud.result&&<div className="modal-backdrop"><section className="game-panel"><div className="eyebrow">MATCH SETTINGS</div><h2>行动设置<span>.</span></h2><p>联机比赛仍在继续。准备好后返回战场。</p><label className="setting-row"><span>鼠标灵敏度</span><b>{settings.sensitivity.toFixed(1)}</b></label><Slider aria-label="鼠标灵敏度" value={[settings.sensitivity]} min={.3} max={2.5} step={.1} onValueChange={value=>onSettings({...settings,sensitivity:Array.isArray(value)?value[0]:value})}/><label className="setting-row sound-setting"><span>游戏音效</span><Switch checked={settings.sound} onCheckedChange={sound=>onSettings({...settings,sound})} aria-label="游戏音效"/></label><button className="primary-button" onClick={onResume}><Play size={18}/> 继续行动</button><button className="text-button" onClick={onLeave}>离开房间，返回模式选择</button><p>WASD 移动 · 左键射击 · 右键切换瞄准<br/>R 换弹 · 1 / 2 切枪 · ESC 设置</p></section></div>}
    {hud.result&&<div className="modal-backdrop"><section className="game-panel result-panel"><div className="eyebrow">MISSION COMPLETE</div><h2>{hud.result==='win'?'行动胜利':hud.result==='loss'?'再接再厉':'势均力敌'}<span>.</span></h2><p>本局比赛已结束</p><div className="result-stats"><div><b>{hud.kills}</b><span>击杀</span></div><div><b>{hud.deaths}</b><span>阵亡</span></div><div><b>{Math.round(300-hud.remaining)}s</b><span>对战时长</span></div></div><button className="primary-button" onClick={onLeave}>返回模式选择</button></section></div>}
    {!hud.connected&&!hud.result&&<div className="network-overlay">连接中断，正在自动重连…</div>}
  </>;
}
