import {useState} from 'react';
import {WEAPONS,WEAPON_IDS,type WeaponId} from '../shared/weapons.ts';
import type {ShopAction,ShopState} from '../shared/economy.ts';
export const shopReason=(reason:string)=>({BUSY:'正在处理，请稍后重试',COMBAT_COOLDOWN:'停止开火或受伤满 2 秒后可购买',INSUFFICIENT_COINS:'金币不足',RESERVE_FULL:'备用弹药空间不足',DEAD:'复活后可以购买',MOVING:'请先停下脚步',IN_COMBAT:'停止开火或受伤满 2 秒后可购买',INSUFFICIENT_FUNDS:'金币不足',NOT_OWNED:'请先购买这把枪',ALREADY_OWNED:'已拥有这把枪',AMMO_FULL:'备用弹药已满或不足一个弹药包的空间',UNLIMITED_AMMO:'手枪备用弹药无限',MATCH_FINISHED:'比赛已经结束',RELOADING:'换弹完成后再购买'} as Record<string,string>)[reason]??reason;
const names={pistol:'半自动手枪',smg:'自动冲锋枪',shotgun:'泵动霰弹枪',rifle:'自动步枪',sniper:'栓动狙击枪'};
export function WeaponPreview({weapon}:{weapon:WeaponId}){
 const color={pistol:'#a7b8c4',smg:'#8ea98b',shotgun:'#be8d65',rifle:'#d3b17c',sniper:'#a6ac85'}[weapon];
 return <svg viewBox="0 0 400 160" aria-label={`${WEAPONS[weapon].name} 枪械侧面预览`}><g fill={color} stroke="#14212a" strokeWidth="3" transform={weapon==='pistol'?'translate(100 10)':''}>
 {weapon==='pistol'?<><path d="M35 40h150v30H80l-15 60H35l12-61H35z"/><path d="M40 45h140v12H40z" fill="#d0dce0"/></>:<><path d="M35 61h160v27H92l-8 41H60l10-41H35z"/><path d="M195 66h130v10H195z"/><path d="M9 60h42v38H9z"/><path d="M111 85h24l9 40h-28z" fill="#293943"/>{weapon==='sniper'&&<><rect x="102" y="28" width="104" height="20" rx="8"/><path d="M130 49v12m40-12v12"/><path d="M315 66h48v10h-48z"/></>}{weapon==='shotgun'&&<rect x="181" y="63" width="61" height="26" rx="5" fill="#9e7453"/>}{weapon==='smg'&&<path d="M111 120v22h28l-5-22z" fill="#293943"/>}{weapon==='rifle'&&<path d="M195 58h58v28h-58z" fill="#344752"/>}</>}
 </g></svg>;
}
export function Shop({state,message,onBuy,onClose}:{state:ShopState;message?:string;onBuy:(action:ShopAction,weapon:WeaponId)=>void;onClose:()=>void}){
 const [selected,setSelected]=useState<WeaponId>('smg');const w=WEAPONS[selected],owned=state.inventory[selected],busy=message==='正在处理…';
 const disabled=!state.canBuy||busy;
 return <div className="shop-backdrop"><dialog open className="armory" aria-modal="true" aria-label="局内商店"><header><div><small>FIELD ARMORY</small><h2>战地商店<span>.</span></h2></div><div className="shop-wallet">金币 <strong>{state.coins}</strong></div><button onClick={onClose}>返回战场 · B / ESC</button></header><div className="armory-body"><nav aria-label="枪械分类">{WEAPON_IDS.map(id=><button key={id} className={id===selected?'selected':''} onClick={()=>setSelected(id)}><b>{WEAPONS[id].name}</b><span>{names[id]}</span><small>{state.inventory[id]?'已拥有':`${WEAPONS[id].price} 金币`}</small></button>)}</nav><article><div className="weapon-preview"><WeaponPreview weapon={selected}/></div><small>{names[selected]}</small><h3>{w.name}</h3><p>{({pistol:'免费保底，精准点射。备用弹药无限，仍需换弹。',smg:'近距离进攻首选，低后坐力与高射速。',shotgun:'贴身爆发，一次发射九颗弹丸，远距离威力明显下降。',rifle:'中距离主力，短点射精准，连续射击需要控制后坐力。',sniper:'远距离精确射击，静止开镜最准确，射后需要拉栓。'})[selected]}</p><dl><div><dt>躯干伤害</dt><dd>{w.damage}{w.pellets>1?` × ${w.pellets}`:''}</dd></div><div><dt>射速 / 分钟</dt><dd>{Math.round(60/w.cadence)}</dd></div><div><dt>弹匣</dt><dd>{w.capacity} 发</dd></div><div><dt>换弹</dt><dd>{w.reload}s</dd></div><div><dt>有效距离</dt><dd>{w.falloffStart}m</dd></div><div><dt>稳定性</dt><dd>{w.stability}/100</dd></div></dl></article><aside><h3>{owned?'已拥有':'购买枪械'}</h3><p>{selected==='pistol'?'默认携带，无需购买。':'首次购买：满弹匣，无备用弹药。'}</p>{selected!=='pistol'&&(!owned?<button className="primary-button" disabled={disabled||state.coins<w.price} onClick={()=>onBuy('buy_weapon',selected)}>购买 · {w.price} 金币</button>:<button className="primary-button" disabled={disabled||state.primary===selected} onClick={()=>onBuy('equip',selected)}>{state.primary===selected?'当前主武器':'装备为主武器'}</button>)}<h3>补充弹药</h3><p>{selected==='pistol'?'无限备用弹药':owned?`弹匣 ${owned.ammo} / ${w.capacity} · 备用 ${owned.reserve} / ${w.reserve}`:'购买枪械后可补充对应弹药'}</p>{selected!=='pistol'&&<button disabled={disabled||!owned||state.coins<w.ammoPrice||(owned?.reserve??0)+w.ammoPack>w.reserve} onClick={()=>onBuy('buy_ammo',selected)}>备用 +{w.ammoPack} 发 · {w.ammoPrice} 金币</button>}<p className="shop-rule">一次携带一把主武器和手枪。<br/>死亡保留装备和剩余弹药。</p><output className="shop-status">{shopReason(message||state.buyBlockedReason)||'可购买 · 对局仍在继续'}</output>{!state.canBuy&&<small>{shopReason(state.buyBlockedReason)}</small>}</aside></div><footer>购买需存活、静止，且最近 2 秒未开火或受伤。打开商店不会获得保护。</footer></dialog></div>;
}
